### ISSUE TITLE
usage run failed

### ISSUE THREAD

**Issue by fawdlstty** [extremecoders-re/bytecode_simplifier#2]
![image](https://user-images.githubusercontent.com/7323999/56259330-385f2100-6105-11e9-96c7-23a9a98ac4f1.png)

[test.zip](https://github.com/extremecoders-re/bytecode_simplifier/files/3087826/test.zip)

**Comment by abel1502** [comment]
As it says, the EXTENDED_ARG opcode's support isn't implemented by now. It is used to extend the following opcode's argument, and specifically in this case - to 'jump' inside a big file. Right now I'm working on implementing this, but it could take quite a while. If the author, @extremecoders-re , agrees to help with it (and more likely lead the implementation with me being almost useless, but still)), it could be implemented soon, but for now all you can do is wait

**Comment by Flarion-ion** [comment]
I`m try to just waiting...(

**Comment by abel1502** [comment]
Oh, sorry, I kind of forgot about it... You see, I got enrolled in a university, and now this is pretty much the busiest year in my life, so I just couldn't find time to implement the remaining parts of the code to make it conveniently usable. I'll most definitely have time to do it in summer, and will try my best to manage it even sooner. Sorry again for the delay(

**Comment by abel1502** [comment]
Alright, try this: https://github.com/abel1502/bytecode_simplifier

(I've made a pull request, but it wasn't accepted yet, so you'll need to use my fork for now)
